server:
  servlet:
    context-path: /persona
spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    show-sql: false
    hibernate:
      ddl-auto: update  
  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/persona
    username: root
    password: password
  